logging:
  file: logs/log.log
  level.com.dafang.monitor.nx: DEBUG
spring:
  datasource:
    druid:
      url: jdbc:mysql://10.172.14.20:6612/sxcc?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      initial-size: 3
      min-idle: 1
      max-active: 50
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.dafang.monitor.nx
  mapper-locations: classpath:mapper/*/*.xml
#  type-handlers-package: com.dafang.monitor.nx.*.entity